# Define the goal
string arm_name
geometry_msgs/Pose recovery_target
geometry_msgs/Pose ee_to_assemble
float32 recover_angle
float32 duration
---
# Define the result
bool is_completed
---
# Define a feedback message
float32 percent_complete1
