# Define the goal
string task_arm
string assist_arm
float32 contact_force
float32 descent_speed
geometry_msgs/Pose task_arm_to_assemble
geometry_msgs/Pose assist_arm_to_target
float32 time_limit
float32 tilt_angle
float32 tilt_duration
int32 state
bool set_tilt

#state
int32 READY = 0
int32 EXEC = 1
int32 TILT_BACK = 2
int32 IGNORE = 3

---
# Define the result
bool is_completed
---
# Define a feedback message
float32 percent_complete
