# Define the goal
string arm_name
float32 linear_vel
float32 pitch
int32 mode
float32 depth
float32 friction
float32 pressing_force
float32 spiral_duration
int32 partial_search_dir
geometry_msgs/Pose ee_to_assemble
float32 range
float32 twist_duration
geometry_msgs/Wrench compensation
bool set_tilt
float32 global_target
bool use_global_depth

# modes
int32 SINGLE_SEARCH=1
int32 DUAL_SEARCH=2
int32 ETC_SEARCH=3

---
# Define the result

bool is_completed
#geometry_msgs/Pose spiral_origin
---
# Define a feedback message
float32 percent_complete
