# Define the goal
float32 speed
float32 upper_speed
float32 duration
float32 contact_force_left
float32 contact_force_right
float32 contact_force_top
string upper_arm
string stop_arm_1
string stop_arm_2

---
# Define the result
bool is_completed
---
# Define a feedback message
float32 percent_complete
