# Define the goal
string arm_name
geometry_msgs/Pose ee_to_assemble
float32 insertion_force
float32 duration
float32 yawing_angle
bool wiggle_motion
bool wiggle_motion_z_axis
bool yawing_motion
int32 connector_type

# connector_type
int32 pin = 0 # pin, bracket
int32 bolt = 1 # bolts

---
# Define the result
bool is_completed
geometry_msgs/Pose end_pose
---
# Define a feedback message
float32 percent_complete
