# Define the goal
string arm_name
geometry_msgs/Pose ee_to_assemble
float32 retreat_force # set positive value
float32 retreat_moment
float32 retreat_distance # set positive value
float32 wiggle_angle
bool wiggle_motion
bool wiggle_motion_z_axis
bool reverse_moment
float32 time_limit
float32 duration
int32 mode

# mode
int32 BOLTING_RECOVERTY = 0
int32 BOLTING_FINISH = 1
---
# Define the result
bool is_completed
string action_result# joint_limit, task_failure, #task_success

---
# Define a feedback message
float32 percent_complete
