# Define the goal
string task_arm
string assist_arm
float32 linear_vel
float32 pitch
int32 mode
float32 depth
float32 friction
float32 pressing_force
int32 spiral_duration
geometry_msgs/Pose ee_to_assemble
float32 range
float32 twist_duration

# modes
int32 SINGLE_SEARCH=1
int32 DUAL_SEARCH=2
int32 ETC_SEARCH=3

# to be deprecated assemble_dir
int32 X_dir=0
int32 Y_dir=1
int32 Z_dir=2

---
# Define the result
bool is_completed
geometry_msgs/Pose spiral_origin
---
# Define a feedback message
float32 percent_complete
