# Define the goal
string arm_name

float32 threshold
float32 search_range
float32 search_duration

geometry_msgs/Pose ee_to_assemble
geometry_msgs/Pose spiral_origin
# modes
int32 SINGLE_SEARCH=1
int32 DUAL_SEARCH=2
int32 ETC_SEARCH=3

#swign_dir
int32 X_dir=0
int32 Y_dir=1
int32 Z_dir=2
---
# Define the result
bool is_completed
std_msgs/Int16MultiArray object_location
---
# Define a feedback message
float32 percent_complete1
